services:
  # MySQL Datenbank
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass123
      MYSQL_DATABASE: craft_db
      MYSQL_USER: craftuser
      MYSQL_PASSWORD: craftpass123
    volumes:
      - db-data:/var/lib/mysql
    restart: unless-stopped

  # Craft CMS Web Server
  web:
    image: craftcms/nginx:8.2
    ports:
      - "8000:80"
    volumes:
      - ./craft-app:/app
      - ./nginx-logs:/var/log/nginx
    depends_on:
      - db
    environment:
      - CRAFT_ENVIRONMENT=dev
      - CRAFT_SECURITY_KEY=your-security-key-here
    restart: unless-stopped

  # N8N Automation
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    volumes:
      - ./n8n-data:/home/node/.n8n
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backups:/backups
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - GENERIC_TIMEZONE=Europe/Berlin
    depends_on:
      - db
    restart: unless-stopped

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: craftuser
      PMA_PASSWORD: craftpass123
    depends_on:
      - db
    restart: unless-stopped

volumes:
  db-data:
    driver: local