# Automatisierter Workflow für CraftCMS Backup und Updates
# Wird ausgelöst durch einen Repository Dispatch Event von außen
name: 💾 CraftCMS Auto Backup & Update

on:
  repository_dispatch:
    # Lauscht auf externe Trigger mit dem spezifischen Event-Type
    types: [run-backup-und-update]

jobs:
  craft-auto-update:
    # Läuft auf Ubuntu (ist günstiger und schneller als Windows/macOS)
    runs-on: ubuntu-latest
    
    services:
      mysql:
        # MySQL 5.7 Service für die Datenbank - ältere Version für Kompatibilität
        image: mysql:5.7
        env:
          # Standard-Zugangsdaten für die Test-Datenbank
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: craft
          MYSQL_USER: craft
          MYSQL_PASSWORD: craft
        ports:
          # MySQL Port 3306 für die Verbindung freigeben
          - 3306:3306
        options: >-
          # Health Check um sicherzustellen, dass MySQL bereit ist
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    
    steps:
      # Repository Code herunterladen
      - name: 📥 Checkout Repo
        uses: actions/checkout@v3
      
      # PHP Umgebung vorbereiten mit allen nötigen Extensions für CraftCMS  
      - name: 📦 Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          # Alle Extensions die CraftCMS braucht
          extensions: mbstring, pdo_mysql, dom, curl, intl, gd, zip, fileinfo
          # Memory Limits erhöhen für größere Projekte
          ini-values: memory_limit=512M, post_max_size=64M, upload_max_filesize=64M
          coverage: none
      
      # Composer Dependencies installieren (PHP Package Manager)
      - name: 🧰 Install Composer
        run: composer install --no-interaction --prefer-dist --optimize-autoloader
        working-directory: ./mein-test-projekt
      
      # Datenbank Backup erstellen bevor wir Updates fahren
      # Sicherheit geht vor - falls etwas schief geht, können wir zurück
      - name: 💾 Backup DB
        run: |
          mkdir -p ./backups
          mysqldump -h 127.0.0.1 -u craft -pcraft craft > ./backups/backup.sql
        working-directory: ./mein-test-projekt
      
      # Das eigentliche CraftCMS Update ausführen
      # 'update all' updated sowohl Craft Core als auch alle Plugins
      - name: 🔁 Run PHP Craft Update
        run: php craft update all
        working-directory: ./mein-test-projekt

 - name: 📝 Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: ✨ Create New Branch and Commit Changes
        run: |
          # Den neuen Branch-Namen erstellen, z.B. "updates/2023-10-27"
          NEW_BRANCH="updates/$(date +%Y-%m-%d)"
          git checkout -b $NEW_BRANCH
          
          # Prüfen, ob es Änderungen gibt (wichtig, damit der Workflow nicht fehlschlägt, wenn keine Updates da waren)
          if [[ -n $(git status -s) ]]; then
            echo "Änderungen gefunden, committe composer.lock..."
            git add ./mein-test-projekt/composer.lock ./mein-test-projekt/composer.json
            git commit -m "chore: Automatisierte Craft CMS Updates"
            git push --set-upstream origin $NEW_BRANCH
          else
            echo "Keine neuen Updates gefunden."
          fi
        env:
          # Token wird für den Push-Befehl benötigt
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # n8n (oder anderen Service) benachrichtigen, dass der Job fertig ist
      # Praktisch für weitere Automatisierung oder Monitoring
      - name: 📡 Webhook Call an n8n
        run: |
          curl -X POST "$N8N_WEBHOOK_URL" \
            -H "Content-Type: application/json" \
            -d '{
              "repo": "'"$GITHUB_REPOSITORY"'",
              "commit": "'"$GITHUB_SHA"'",
              "event": "craft-update-done",
              "status": "success"
            }'
        env:
          # Webhook URL aus den Repository Secrets laden (sicherer)
          N8N_WEBHOOK_URL: ${{ secrets.N8N_WEBHOOK_URL }}
      
      # Erfolgsmeldung in den Logs
      - name: ✅ Done
        run: echo "Backup und Update abgeschlossen!"
